include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
    unnecessary_new: ignore
    unnecessary_const: ignore
    unused_local_variable: ignore
    must_be_immutable: ignore
  exclude:
    - lib/packages/**.*
    - .dart_tool/**.*
    - .editorconfig
    - .flutter-plugins
    - .flutter-plugins-dependencies
    - .gitignore
    - .idea/**.*
    - .pre-commit-config.yaml
    - .vscode/**.*
    - README.md
    - android
    - assets/**.*
    - build.sh
    - build.yaml
    - build/**.*
    - format.sh
    - gen/**.*
    - ios/**.*
    - l10_gen.sh
    - l10_pre.sh
    - lib/**.g.dart
    - lib/l10n/**.*
    - linux/**.*
    - localizations_generate.sh
    - localizations_prepare.sh
    - macos/**.*
    - other/**.*
    - plugins/**.*
    - pre-commit.sh
    - pubspec.lock
    - pubspec.yaml
    - readmebase64
    - rebuild.sh
    - res/**.*
    - test/**.*
    - test_driver/**.*
    - lib/data/network/model/**.*
    - lib/domain/models/**.*
    - lib/feature/favorites/redux/state/**.*
    - lib/feature/recharge/domain/state/**.*
    - version.properties
    - vlc_log.txt
    - web/**.*

linter:
  rules:    
    # - always_specify_types
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - flutter_style_todos
    - implementation_imports
    - iterable_contains_unrelated_type
    - no_duplicate_case_values
    - no_logic_in_create_state
    - non_constant_identifier_names
    - package_names
    - package_prefixed_library_names
    - prefer_collection_literals
    - prefer_conditional_assignment
    # - prefer_const_declarations
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - recursive_getters
    - slash_for_doc_comments
    - sort_pub_dependencies
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_statements
    - unnecessary_string_interpolations
    - unrelated_type_equality_checks
    - valid_regexps